### ISSUE TITLE
Mass export/import images - SOR4

### ISSUE THREAD

**Issue by AyanamiRei1** [FanTranslatorsInternational/Kuriimu2#105]
In Streets of Rage 4 the SOR4 characters have over 100 frames/sprites and having to manually export and then import each sprite isn't very practical it's doable with the classic versions of the characters as they have under 100 sprites. 

Take SOR4 Blaze for example she has 200 sprites not including her special move sprites the way SOR4Explorer did things was it just let you drag and drop some images over the pre-existing sprites while with this you have to export the file, open the file and then import the images one by one if you can imagine doing that for a character that has 200 sprites it sounds awful.

I did try using the batch injector but that didn't seem to work at all and the batch extractor extracted the images but as a folder instead of being named sor3_blaze0001, 2 ,3 for example but instead they're all named 00 and they're in a folder named sor3_blaze0001, 2 ,3.

So in the end I'm asking for something like SOR4Explorer but for the Switch version it possible as this might be outside the scope of Kuriimu2.

Thanks!

**Comment by onepiecefreak3** [comment]
Extract everything with the batch extractor, replace your images in there, and then use the batch injector to reinject what the batch extractor extracted. Both tools are meant to work in tandem and need to do more than just the specialized injection of for example the SOR4Explorer.

Also, the 00 part of each extracted file is also something K2 needs, since it needs to keep track of the index the image has in the file. Otherwise it cannot inject images into formats that have more than one image.

Since both, batch extractor and injector do work, and would solve this issue, I'm inclined to already close it again. Please refer to our discord if you have questions using the batch dialogs. I will let you close this issue after you're done.

**Comment by AyanamiRei1** [comment]
Do you have a link to this discord even though the files are named correctly and are in the folder the batchinjector doesn't work for me at least

**Comment by onepiecefreak3** [comment]
https://discord.gg/S9Qg4eXw

**Comment by AyanamiRei1** [comment]
Thank you of course the moment I join the server I actually figure out how to use it turns out I was doing it backwards. Sorry about all the hassle
