### ISSUE TITLE
obb archive in Ace Attorney: Dual Destinies for android

### ISSUE THREAD

**Issue by Ludio22** [FanTranslatorsInternational/Kuriimu2#113]
**Game Name: Ace Attorney: Dual Destinies**  
**Console: Android**  
**Format extension(s): obb**  
**Type: archive** 

**Bug details:**
The game cache for android, contains 2 obb files, main and patch, main is unpacked but patch cannot be opened.

**Sample files:**
https://mega.nz/file/e59wkCKQ#3L3px6dCoLgP9fsN2S4I5ldJHaL3Rkjo7iVIY3E8Ro8

**Comment by wabberz** [comment]
It's a standard ZIP archive that contains the cutscenes. Use the archiver of your choice to unpack it. 7zip and WinRAR will do nicely.

**Comment by onepiecefreak3** [comment]
As uwabami stated, the patch.obb (as with most obb's in Android apps) is a normal zip file. You can use any editor you like, that can open zip files.
Kuriimu2 currently has no support for zip files, since we focus around file formats that aren't (widely) support by standardized tools already.

Capcom has the characteristic of packing their "main" archive of file data in their own way. And since the content of an obb can be fully custom, they decided to go with their own format. They didn't do that for patch.obb however.

Therefore, this is a non-issue and closed.
