### ISSUE TITLE
The Great Ace Attorney: Chronicles files not openable 

### ISSUE THREAD

**Issue by JayFaraday** [FanTranslatorsInternational/Kuriimu2#163]
With the release of TGAAC comes, I'm sure, a myriad of issues. My team and I have encountered the following:
-ARC files are not openable. I tried ArcTool, the game itself created this log file, if it helps at all:
```
RE6 tex format selected.
Console platform was defined, but this is a PC ARC.
Wrote C:\Program Files (x86)\Steam\steamapps\common\TGAAC\nativeDX11x64\archive\GO\chr000\GO\obj\chr\chr000\model\chr000_face_BM_NOMIP.00000000 (copied)
```
-TEX files are openable, but do not seem to display properly. Here's the image:
![title_2_BM_NOMIP_HQ_eng tex 00](https://user-images.githubusercontent.com/29417893/127099028-eac44ada-82e4-475b-b0f9-b4f9f45bdd2a.png)

We can't really start ripping this game until we can get into these two file types.

**Comment by onepiecefreak3** [comment]
Tests were already conducted, and while TEX does need a small fix due to unknown or misused image encodings, the ARC's work as expected without any changes.
We did however, find out that the release builds seem to have a broken version of the mt_framework plugin, which is not the case for dev builds. Please get yourself the newest dev build and conduct all your tests again.

Also this issue does not follow our issue templates and is missing sample files to work out any subsequent flaw.
After the TEX fix is committed later this day, this issue will be closed. Please open another issue if you find more in the future, with the proper information to work with.

**Comment by quiple** [comment]
[https://mega.nz/file/HF4g0AQJ#xx6EYQLR63KdLi-9V0mbgP0nQeFqATC91c40Hgurj-M](https://mega.nz/file/HF4g0AQJ#xx6EYQLR63KdLi-9V0mbgP0nQeFqATC91c40Hgurj-M)
A sample file from The Great Ace Attorney Chronicles.

**Comment by onepiecefreak3** [comment]
With the newest dev build all currently known issues (like the ones here, or reported privately) seem to be fixed. Please open another issue with proper description of the error and samples, if you find some that still not work.
Issue closed.
