### ISSUE TITLE
.PKB compression error

### ISSUE THREAD

**Issue by BWAH2leaf** [FanTranslatorsInternational/Kuriimu2#173]
**Game Name:**  Tales Of the Abyss
**Console:**  Ps2
**Format extension(s):**  .PKB
**Type:** [ text | image | archive | font ] Archive

**Bug details:**

.PKB file is 0x03 in first byte. so can decompression with Kuriimu2 compression menu.(Compression Extensions is TalesOfLz "Lz03")

but, compression is wrong.
1. ".PKB.out"(decomp) compression.
2. ".PKB.out.out"(comp) is Decompression.
3. ".PKB.out.out.out"(decomp) is different ".PKB.out"(decomp)

**Sample files (if possible):**

https://mega.nz/file/KKoW2DiS#Mj_242MY-lDpRMZk1WQJZaKzU380PifOYWVYMZrRbyg

**Comment by onepiecefreak3** [comment]
This issue is fixed in the newest dev build.
The compression supports both pattern matching and run length. When the base framework was refactored, the information for the compression piepline got lost, that RLE should be used.
Also, for pattern matching, it was fixed that the correct offset to the pattern is saved. This calculation was off, due to another refactoring changing the base position on which matches are given into the encoder.

Thos changes also greatly increased compression speed.

**Comment by BWAH2leaf** [comment]
This issue is closed??

compression is working, but in game playing crashed.
( i was original file > decompress in Kuriimu2 > compress in Kuriimu2, and replace original comp file to Kuriimu2 compression file. )

You said you've modified some compression methods, could that be the reason for not being able to load?

**Comment by onepiecefreak3** [comment]
The file could be decompressed to look like the original file. Therefore, it's less likely by now that the compression is responsible for a Load error. This lead to the issue being closed, since all issues regardign the compression are provably fixed.
If the game still doesn't load the files, that's another issue and not part of this one. So create a new one.
