### ISSUE TITLE
LEVEL 5 - G4TX 

### ISSUE THREAD

**Issue by gyeoll** [FanTranslatorsInternational/Kuriimu2#18]
Issue: Plugin Request
Console: Switch
Format extension(s): .G4TX
Type: Graphic (Texture)
Game Name: You kai gakuen ~wai wai gakuen sekasu~ (妖怪学園Y ～ワイワイ学園生活～)
First 8 byte of file(s): 47 34 54 58 60 00 65 00 (G4TX`.e.)

More details:
Error message : https://drive.google.com/file/d/11FcufGl_gEYiCvkGNK1B0d69zD7P_AlU/view?usp=sharing

Sample files (if possible): https://drive.google.com/file/d/1b6If9BRUutVzIhmIpRVMtt310XSJe45E/view?usp=sharing

**Comment by onepiecefreak3** [comment]
Since the files need to be access requested, we can only assume which files report this error.
However, after researching the game itself we could determine that encoding 77 maps to BC7, which is already supported by the Level5 plugin from RElease 1.2.0 onwards.
Therefore this issue is not reproducable anymore and solved.

Side note: The latest refactoring of the G4TX plugin that also solved this issue, was based on the mentioned game. All encodings found in said game are supported at least. If there are more encodings found for G4TX that are unsupported, make another issue.
