### ISSUE TITLE
Spirit of Justice Mobile MT TEX Error

### ISSUE THREAD

**Issue by TypeBrince** [FanTranslatorsInternational/Kuriimu2#180]
**Game Name:**  Ace Attorney Spirit of Justice
**Console:**  Android
**Format extension(s):**   .tex
**Type:** Image

**Bug details:**
When trying to open up certain .tex files using Kuriimu 2, I receive the error "The given key '12' was not present in the dictionary." This also happened with some Dai Gyakuten Saiban 2 .tex files from android too. I noticed when batch converting that the program had errors and tried them individually.

**Sample files (if possible):**
Here are some of the files that I received this issue. Happy to provide more if needed.
https://drive.google.com/drive/folders/1B28AHEI5yLHdwLQMMnThn3XPz7OS9nwt?usp=sharing

**Comment by TypeBrince** [comment]
<img width="358" alt="Screen Shot 2021-08-23 at 15 27 32" src="https://user-images.githubusercontent.com/71999140/130395019-00aaf3b8-3074-4194-ba8e-266fd6ba1830.png">
This is what the error message looks like, btw

**Comment by onepiecefreak3** [comment]
This bug was introduced when the Mobile MtTex part of the plugin was refactored. This part of the code originally checked the file size against a predicted size to determine which variant of mobile format is given to the plugin. The size determination required the bitdepth of the encoding specified in the header of the Tex, but for one variation the format is 0xC, which is a special placeholder for GPU dependant encodings and had no single encoding mapped to it, which lead to this issue.
It's quite the big issue that went under the radar since the refactoring, due to not being tested on those TEX affected at the time.

The bug is fixed i nthe newest dev build and upcoming Release 1.2.2.
