### ISSUE TITLE
Install steps not clear in README

### ISSUE THREAD

**Issue by Fusseldieb** [FanTranslatorsInternational/Kuriimu2#312]
I've downloaded countless of runtimes, both x86 and x64, and even restarted, to no avail. 
<img src="https://github.com/FanTranslatorsInternational/Kuriimu2/assets/4715129/2fd955c0-1671-4822-a0c9-50db0db45a91" height="200px">

The install steps are unclear and the dialog doesn't do anything if "Yes" is clicked:
<img src="https://github.com/FanTranslatorsInternational/Kuriimu2/assets/4715129/576f8ce0-9e76-474c-aaa3-6a80a76ce513" height="100px">

Putting links to the correct runtimes in the README would be immensely helpful.

**Comment by Fusseldieb** [comment]
After a LOT of trial and errors, what ended up working was installing exactly this: **.NET Core 3.1 Desktop Runtime**

Link below:

https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-3.1.32-windows-x64-installer

**Comment by Drflash55** [comment]
> Fusseldieb said:
> After a LOT of trial and errors, what ended up working was installing exactly this: **.NET Core 3.1 Desktop Runtime**

This also worked for me. This **DEFINITELY** should've been more specific about what you needed to *actually* run it.

**Comment by onepiecefreak3** [comment]
The READ.ME clearly states: "You need to have the .Net Core Desktop Runtime 3.1.6 installed on your system."
You instead installed the .Net Core Desktop Runtime 3.1.32 now, to which you linked.

I'm unsure how it can be made even more clear? Since the name matches exactly what you were supposed to do. And since the download page of Microsoft changes for that runtime quite often, we won't put a link there.

I'd like a clearer suggestion as to what could be changed, as I don't really see it.

**Comment by Fusseldieb** [comment]
> I'd like a clearer suggestion as to what could be changed, as I don't really see it.

As I said in my original post, I downloaded heaps of different versions. They all have ".Net" in it. Not being a .Net developer, this confused me as heck. 
I literally almost gave up.

My suggestion would be to hyperlink the name in the README, so it redirects to the RIGHT download page.

**Comment by onepiecefreak3** [comment]
But the name is very clearly written in there, as I quoted in my reply. It's ".Net Core Desktop Runtime".
And as I said, the link structure of the microsoft pages regularly change, so a hyperlink is not maintainable.

If this isn't enough, I'm not sure what more I can do.

**Comment by Fusseldieb** [comment]
> But the name is very clearly written in there, as I quoted in my reply. It's ".Net Core Desktop Runtime". And as I said, the link structure of the microsoft pages regularly change, so a hyperlink is not maintainable.
> 
> If this isn't enough, I'm not sure what more I can do.

The real issue is that if I go onto the "Net Core" download page, I get plastered with links and downloads, none of which explicitly tell you "on, this one is the right one".

![image](https://github.com/FanTranslatorsInternational/Kuriimu2/assets/4715129/c404acae-7e43-4d7f-a92d-46c63e875d13)

A inexperienced user will definitively not know what to choose.

**Comment by onepiecefreak3** [comment]
The READ.ME clearly tells you to download ".Net Core Desktop Runtime" and you clearly have a section there titled exactly that. And since the READ.ME also specifies that x64 is required you can only click one link.

I'm still struggling to see the issue. Even if there are many links, you only need that name to figure out on which link to click.

**Comment by Fusseldieb** [comment]
> he READ.ME clearly tells you to download ".Net Core Desktop Runtime" and you clearly have a section there titled exactly that.

Nope, there's a section called ".Net Desktop Runtime 3.1" and then there's "ASP.Net **Core** Runtime 3.1". I thought the one with "Core" in it was the right one. It wasn't.

**Comment by onepiecefreak3** [comment]
While I'm not sure how "ASP.NET Core Runtime" is somehow more logical than ".NET Desktop Runtime", even though more words match (if not exactly match, I'll give you that one), I will remove "Core" from the READ.ME in the installation instructions.

Otherwise I will close this issue now. Without offending you or the other user that responded, I asked around some of the less knowledgable people on our discord, and they didn't struggle as much or at all. So, I will make the change I mentioned and will not waste anymore time on this.

Thanks for the feedback anyway. Hopefully this small change helps someone else out.

**Comment by Fusseldieb** [comment]
Now it's clearer! Thank you.
