### ISSUE TITLE
Issue with SpikeChunsoft Lz

### ISSUE THREAD

**Issue by obluda3** [FanTranslatorsInternational/Kuriimu2#40]
Game Name:  Inazuma Eleven Go Strikers 2013
Console:  Wii
Format extension(s): SHTXFF  
Type: image

Bug details: When I try to compress this file using SpikeChunsoftLz, the compression never ends (meaning it doesn't produce me a compressed file), I kept it going for more than 20 minutes.

Sample file:  
https://drive.google.com/file/d/1aBjfQfmFvHek6ISz3TbC0w4Zn7gzyQwk/view?usp=sharing

**Comment by onepiecefreak3** [comment]
The base problem is the optimal parser. To properly find the optimal path through the data it calculates a match per position. Not only is the file pretty large, but it also contains of massive repeatable data. This, combined with the infinite length of a match per position, leads to the match finder needing more and more time per position to find the end of a match.

I have to think about a proper solution to this, since it will have a large effect for the compression itself.

**Comment by obluda3** [comment]
Here's the unmodified compressed file (and the decompressed one too) : https://drive.google.com/drive/folders/1mJ_J4H59snS3YeMQSEPDLG5TTmEEk9hh?usp=sharing

**Comment by obluda3** [comment]
I managed to compress the file using Kuriimu1.
