### ISSUE TITLE
Issues with Yo-kai Watch 1 Nintendo Switch image reading

### ISSUE THREAD

**Issue by DrgnMasterKota** [FanTranslatorsInternational/Kuriimu2#41]
Game Name:  Yo-kai Watch 1
Console:  Nintendo Switch
Format extension(s): .xi
Type: Image 

More details:  
It seems Kuriimu2 can open Level-5's .xi image format like the original incarnation can, but it seems Level-5 has slightly modified their .xi format for Switch because there's some issues with image reading.

Sample files:  
https://drive.google.com/file/d/1_YTji0PzbCuTkPFTWJxEBvnyux3A714k/view?usp=sharing

**Comment by onepiecefreak3** [comment]
Full support for .xi files from the Switch is added in the newest dev build and upcomgin Release 1.2.1
This format has no breaking changes to earlier iterations beside having the magic number "IMGN" (for IMaGe Nx) and a different mapping of image encodings.

If you find images that can't be loaded, since an encoding is not yet supported, create a new issue stating this accordingly!
