### ISSUE TITLE
Cannot execute at all

### ISSUE THREAD

**Issue by plulilith** [FanTranslatorsInternational/Kuriimu2#60]
I can't  build and execute Kuriimu2 using vs 2019.
Can someone help me ?

Thanks,

**Comment by onepiecefreak3** [comment]
There are so many information missing here.
Which OS, which branch of source did you use?
Are there any errors? If not, did you even install .Net Core to build and run our app (you obviously need it installed even for compilation)
If you can't build it, what are the compiler errors?

**Comment by plulilith** [comment]
thanks for your reactivity,

i'm on windows10, sry but idk which branch i used, maybe if you give me a few example i could tell you.
I installed the latest version of .net Core 
I have a trouble when building it, there are those errors:
"
Error	CS1503	Argument 1 : cannot convert 'Kuriimu2.Wpf.ViewModels.ConcurrentProgress' to 'string'	Kuriimu2.Wpf	C:\Users\Yèsmyn\Desktop\JOHN\Kuriimu2-master\src\Kuriimu2.Wpf\ViewModels\ShellViewModel.cs	34	Actif

**Comment by plulilith** [comment]
Others errors came out when I tried, im making you a list

**Comment by onepiecefreak3** [comment]
I'm not sure if you even should build Kuriimu2 yourself. You don't seem to have the knowledge for that.
Otherwise you would notice that what you downloaded tells you the branch already, it's the master branch.
Wpf is not buildable for a long time, so you may ignore that. Instead build Kuriimu2.WinForms, or Kuriimu2.CommandLine, or Kuriimu2.EtoForms.
Also, installing the latest .Net Core is not correct either. If you would have read the READ.ME of this project (which you would have done, if you know what you're doing), you would have noticed the requirement to be .Net Core 3.1.302.

If you want a functional build of Kuriimu2, just to use it, follow the instructions in the READ.ME to download an already working build of it.

**Comment by plulilith** [comment]
Understood, I'm gonna fix that 
Just a last question, is there a difference between branches? 
As I'm trying to open a .fa archive, is a branch more useful than an other ?

**Comment by onepiecefreak3** [comment]
Both branches should currently be in a state to open .fa files. So in regards to that, no, there is no difference.

**Comment by plulilith** [comment]
Ok great, thanks a lot for your reactivity and your help :)

**Comment by onepiecefreak3** [comment]
I will close this issue then, since it seems to be resolved.
In the future, please state your problems with more detail, otherwise it will be immediately closed.
